chore: (mender/rauc) add `tedge config upgrade` and `tedge refresh-bridges` to verification step
Signed-off-by: Rina Fujino <rina.fujino.23@gmail.com>

diff --git a/meta-tedge-mender/recipes-tedge/tedge-state-scripts/tedge-state-scripts/verify-tedge b/meta-tedge-mender/recipes-tedge/tedge-state-scripts/tedge-state-scripts/verify-tedge
--- a/meta-tedge-mender/recipes-tedge/tedge-state-scripts/tedge-state-scripts/verify-tedge
+++ b/meta-tedge-mender/recipes-tedge/tedge-state-scripts/tedge-state-scripts/verify-tedge
@@ -10,7 +10,7 @@ MAPPERS="c8y az aws"
 is_mapper_connected() {
     CLOUD_MAPPER="$1"
 
-    if [ -n "$(tedge config get "$CLOUD_MAPPER.url" 2>/dev/null)" ]; then
+    if [ -n "$(tedge config get "${CLOUD_MAPPER}.url" 2>/dev/null || tedge config get "${CLOUD_MAPPER}.mqtt" 2>/dev/null)" ]; then
         tedge connect "$CLOUD_MAPPER" --test >&2
     else
         # If the configuration is not configured, then treat the device as healthy
@@ -32,9 +32,26 @@ all_healthy() {
     return "$failed"
 }
 
-# Try fixing any possible mosquitto permissions first
-# In case if the pervious image uses different uid/gid for the mosquitto user
-chown mosquitto:mosquitto /etc/tedge/device-certs/* ||:
+    # upgrade the config to move out the mapper specific settings from tedge.toml (tedge version >= 2.0.0)
+    if tedge config upgrade --help >/dev/null 2>&1; then
+        if ! tedge config upgrade; then
+            code="$?"
+            echo "ERROR: 'tedge config upgrade' failed. code=$code" >&2
+            exit "$failed"
+        fi
+    else
+        # Try fixing any possible mosquitto permissions first
+        # In case if the pervious image uses different uid/gid for the mosquitto user
+        chown mosquitto:mosquitto /etc/tedge/device-certs/* ||:
+    fi
+
+    if tedge refresh-bridges --help >/dev/null 2>&1; then
+        if ! tedge refresh-bridges; then
+            code="$?"
+            echo "ERROR: 'tedge refresh-bridges' failed. code=$code" >&2
+            exit "$failed"
+        fi
+    fi
 
 if ! all_healthy; then
     exit "$RETRY_LATER"
